<?php

define('PARSHIOS', [
    'Breishis',
    'Noach',
    'Lech Licha',
    'Vayera',
    'Chaye Sara',
    'Toldos',
    'Vayetzei',
    'Vayishlach',
    'Vayeshev',
    'Miketz',
    'Vayigash',
    'Vayichi',
    'Shmos',
    'Vaeira',
    'Bo',
    'Bishalach',
    'Yisro',
    'Mishpatim',
    'Terumah',
    'Tetzaveh',
    'Ki Sisa',
    'Vayakheil',
    'Pekudei',
    'Vayikra',
    'Tzav',
    'Shmini',
    'Tazria',
    'Metzora',
    'Acharei Mos',
    'Kedoshim',
    'Emor',
    'Behar',
    'Bechukosai',
    'Bamidbar',
    'Naso',
    'Behaaloscha',
    'Shlach',
    'Korach',
    'Chukas',
    'Balak',
    'Pinchas',
    'Matos',
    'Masei',
    'Dvarim',
    'Vaeschanan',
    'Eikev',
    'Reeh',
    'Shoftim',
    'Ki Seitzei',
    'Ki Savo',
    'Nitzavim',
    'Vayelech',
    'Haazinu',
    'Vezos Haberacha',
]);
