name: lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master

      - name: Install dependencies
        run: composer install

      - name: Execute linter
        run: composer run-script lint:test | cs2pr
