name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1", "8.2"]
        dependencies:
          - "lowest"
          - "highest"

    runs-on: ubuntu-latest

    name: "PHP${{ matrix.php }} ${{ matrix.dependencies == 'highest' && '↑' || '↓' }}"

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Install lowest dependencies from composer.json
        if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-progress --prefer-lowest

      - name: Install highest dependencies from composer.json
        if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress

      - name: Check PSR-4 mapping
        run: composer dump-autoload --optimize --strict-psr

      - name: Execute unit tests
        run: composer run-script test
